# 头部菜单，title: link
menu:
  分类: /categories
  标签云: /tags
  归档: /archives
  知乎: https://zhihu.com/people/hbxyxuxiaodong
  知乎专栏: https://zhuanlan.zhihu.com/yanyunchangfeng
  github: https://github.com/yanyunchangfeng
  gitee: https://gitee.com/yanyunchangfeng
  twitter: https://twitter.com/yanyunchangfeng
  medium: https://medium.com/@yanyunchangfeng
  
# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: true

# 默认音乐
mp3: 
  - /media/qsx.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: https://user-gold-cdn.xitu.io/2019/5/26/16af37f281b9f8b8?w=1920&h=1200&f=jpeg&s=645059 # /img/welcome-cover.jpg

# 默认文章封面图
cover: https://user-gold-cdn.xitu.io/2019/5/26/16af3802a2370fe1?w=500&h=375&f=png&s=339961

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '45d1e04f5d74744344b5'
    # 应用秘钥
    clientSecret: '7896d2f0a681f1ec6b827d1b7396c7aa15bec3be'
    # issue仓库名
    repo: 'yanyunchangfeng.github.io'
    # Github名
    owner: 'yanyunchangfeng'
    # Github名
    admin: ['yanyunchangfeng']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: true

# 网站关键字
keywords: yanyunchangfeng 

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-140908492-1

# 网站ico
favicon: https://user-gold-cdn.xitu.io/2019/5/26/16af3802a2370fe1?w=500&h=375&f=png&s=339961

# rss文件
rss: atom.xml


